# Streamlit Cloud Secrets Configuration
# This file contains sensitive information that will be encrypted and served securely
# Learn more: https://docs.streamlit.io/streamlit-cloud/get-started/deploy-an-app/connect-to-data-sources/secrets-management

# Example API Keys (uncomment and add your actual keys when needed)
# [api_keys]
# openai_api_key = "your-openai-api-key-here"
# google_maps_api_key = "your-google-maps-api-key-here"
# sports_api_key = "your-sports-api-key-here"

# Database Configuration (if you add database functionality)
# [database]
# host = "your-database-host"
# port = "5432"
# database = "your-database-name"
# username = "your-username"
# password = "your-password"

# Email Configuration (for newsletter functionality)
# [email]
# smtp_server = "smtp.gmail.com"
# smtp_port = "587"
# sender_email = "your-email@gmail.com"
# sender_password = "your-app-password"

# Social Media API Keys (if you add social features)
# [social]
# twitter_api_key = "your-twitter-api-key"
# facebook_app_id = "your-facebook-app-id"
# instagram_access_token = "your-instagram-token"

# App Configuration
[app]
debug_mode = "false"
max_file_size_mb = "50"
allowed_file_types = ["mp4", "mov", "avi"]

# Analytics (if you add analytics)
# [analytics]
# google_analytics_id = "GA-XXXXXXXXX"
# mixpanel_token = "your-mixpanel-token"